[theme]
base="light"
backgroundColor="#F5F5F5"
secondaryBackgroundColor="lavender"
codeBackgroundColor="powderBlue"

[theme.sidebar]
backgroundColor="#8DBCC7"
secondaryBackgroundColor="white"
textColor="black"